version: '3'
services:
  backend:
    build: "./api"
    ports:
      - "8080:8080"
  frontend:
    build: "./app"
    environment:
      - API_BASE_URL=http://backend:8080
    ports:
      - "8081:8081"
  